.ssh_connection_alpine_template:
  before_script:
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - cp "$GL_SSH_PRIVATE_KEY_FILE" ~/.ssh/id_ed25519
    - chmod -R 600 ~/.ssh
    - echo "$GL_SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
